services:
    kopia:
        image: kopia/kopia:latest
        hostname: kopiahost 
        container_name: Kopia
        restart: unless-stopped
        ports:
            - 51515:51515
        # Setup the server that provides the web gui
        command:
            - server
            - start
            - --disable-csrf-token-checks
            - --insecure
            - --address=0.0.0.0:51515
            - --server-username=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            - --server-password=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        environment:
            # Set repository password
            KOPIA_PASSWORD: "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
            USER: "root"
        volumes:
            # Mount local folders needed by kopia
            - ./config:/app/config
            - ./cache:/app/cache
            - ./logs:/app/logs
            # Mount local folders to snapshot
            - ./data:/data:ro
            # Mount repository location
            - ./repository:/repository
            # Mount path for browsing mounted snaphots
            - /tmp/kopia/shared:/tmp:shared
