services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    volumes:
      - ./config:/config
      - ./cache:/cache
      - type: bind
        source: /media/eagleson/Media/jellyfin
        target: /media
    ports:
      - 8096:8096
    restart: 'unless-stopped'